### ISSUE TITLE
npm test missing .babelrc and ReferenceError: MongoID is not defined

### ISSUE THREAD

**Issue by lc3t35** [inProgress-team/react-native-meteor#290]
When I tryed npm test, I had this error due to the missing .babelrc file in the repo 
````
/Users/laurent/dev/meteor/react-native-meteor/test/lib/ddpShould.js:3
import DDP from '../../lib/ddp';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at loader (/Users/laurent/dev/meteor/react-native-meteor/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/laurent/dev/meteor/react-native-meteor/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/laurent/dev/meteor/react-native-meteor/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/laurent/dev/meteor/react-native-meteor/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/laurent/dev/meteor/react-native-meteor/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/laurent/dev/meteor/react-native-meteor/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
npm ERR! Test failed.  See above for more details.
````
Solved by adding .babelrc file with 
````
{
 "presets": [ "es2015" ]
}
````
Then next error is 
````
> react-native-meteor@1.2.0 test /Users/laurent/dev/meteor/react-native-meteor
> mocha --compilers js:babel-core/register --require test/setup --recursive

/Users/laurent/dev/meteor/react-native-meteor/lib/mongo-id.js:12
MongoID = {};
        ^

ReferenceError: MongoID is not defined
    at Object.<anonymous> (/Users/laurent/dev/meteor/react-native-meteor/lib/mongo-id.js:4:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/laurent/dev/meteor/react-native-meteor/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/laurent/dev/meteor/react-native-meteor/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/laurent/dev/meteor/react-native-meteor/lib/socket.js:3:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/laurent/dev/meteor/react-native-meteor/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/laurent/dev/meteor/react-native-meteor/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/laurent/dev/meteor/react-native-meteor/lib/ddp.js:8:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/laurent/dev/meteor/react-native-meteor/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/laurent/dev/meteor/react-native-meteor/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/laurent/dev/meteor/react-native-meteor/test/lib/ddpShould.js:2:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/laurent/dev/meteor/react-native-meteor/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/laurent/dev/meteor/react-native-meteor/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/laurent/dev/meteor/react-native-meteor/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/laurent/dev/meteor/react-native-meteor/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/laurent/dev/meteor/react-native-meteor/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/laurent/dev/meteor/react-native-meteor/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
npm ERR! Test failed.  See above for more details.
````

**Comment by charpeni** [comment]
Should be fixed in `1.3.0`.
